baseURL = 'https://a7med7x7.github.io/'
languageCode = 'en-us'
title="Ahmed Alghali Blog"
theme="nightfall"

[params]
user = "a7"
hostname = "github.io"

[params.author]
name = "A.Alghali"
#avatar = "assets/pfps/avatar.jpg"
avatarSize = "size-m"
email = "ahmed@offsechq.com"
avatarFirst = false


[[params.social]]
key = 1
name = "twitter"
url = "https://twitter.com/a7med7alghali"
icon = "fa-brands fa-twitter"
target = "_blank"
aria = "Twitter Profile"

[[params.social]]
key = 2
name = "email"
url = "ahmed@offsechq.com"
icon = "fa-solid fa-envelope"
aria = "Email Ahmed"

[params.styles]
color = "blue"

[menu]
  [[menu.header]]
    name = "blogs"
    weight = 0
    url = "/posts"