baseURL = 'https://a7med7x7.github.io/'
languageCode = 'en-us'
title="Ahmed Alghali Blog"
theme="nightfall"

[params]
user = "a7"
hostname = "github.io"

openLinksInNewTab = true

showMetadata = true       # Master switch for all metadata display
showPublishedDate = true  # Show published date on post page
showReadingTime = true    # Show reading time on post page
showTags = true           # Show tags on post page
showCategories = true     # Show categories on post page


[params.author]
name = "A.Alghali"
#avatar = "assets/pfps/avatar.jpg"
avatarSize = "size-m"
email = "ahmed@offsechq.com"
avatarFirst = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[pagination]
pagerSize = 6
paginate = 5

[[params.social]]
key = 0
name = "github"
url = "https://github.com/a7med7x7"
icon = "fa-brands fa-github"
target = "_blank"
aria = "GitHub Profile"

[[params.social]]
key = 1
name = "twitter"
url = "https://twitter.com/a7med7alghali"
icon = "fa-brands fa-twitter"
target = "_blank"
aria = "Twitter Profile"

[[params.social]]
key = 2
name = "email"
url = "ahmed@offsechq.com"
icon = "fa-solid fa-envelope"
aria = "Email Ahmed"

[params.styles]
color = "blue"

[menu]
  [[menu.header]]
    name = "blogs"
    weight = 0
    url = "/posts"